### ISSUE TITLE
[BUG]尝试编辑服务器信息时软件闪退

### ISSUE THREAD

**Issue by nita0318** [HMBSbige/ShadowsocksR-Windows#128]
**描述 bug**

右键托盘图标尝试编辑服务器信息时软件闪退，并且快速闪现一个错误窗口

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 右键软件托盘图标
2. 进入菜单->服务器->编辑服务器

**预期行为**

软件直接闪退

**截图**

![2019-10-30_17-27-34 00_00_22_39 Still001](https://user-images.githubusercontent.com/49789145/67847379-b92fb880-fb3d-11e9-8235-01da2c24ef39.png)

**环境**

 - 系统：Windows 10 1903 18362.418
 - 程序版本：5.1.5.0 ShadowsocksR-netcore-win64
 
**其它内容**

服务器信息来自订阅链接

文字版错误报告，来自日志查看器
[Error] System.IO.FileNotFoundException: 
File name: 'Syncfusion.Tools.Wpf, Version=17.3300.0.17, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89'
   at Shadowsocks.View.ConfigWindow..ctor(ShadowsocksController controller, Int32 focusIndex)
   at Shadowsocks.Controller.MenuViewController.ShowConfigForm(Boolean addNode)
   at Shadowsocks.Controller.MenuViewController.Config_Click(Object sender, EventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Shadowsocks.Program.Main(String[] args)

**Comment by HMBSbige** [comment]
这种 NotFound 一看就是被清理软件清理了 DLL

详情见 [Wiki](https://github.com/HMBSbige/ShadowsocksR-Windows/wiki/ShadowsocksR-Windows-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#artifacts)

日常使用推荐使用上面两个版本
