### ISSUE TITLE
v5.0.1.2无法打开网页

### ISSUE THREAD

**Issue by haley924** [HMBSbige/ShadowsocksR-Windows#56]
昨天接到更新通知，下载了v5.0.1.2，增加了鼠标滑轮功能，很是方便，但问题是有部分人用着正常，但有部分比如说我却打不开网页，TELEGRAM设置中设了IP和SSR的1080端口，也能用，但浏览器打开需要代理的网站就打不开了，比如说油管推特等等！我是从你们这个低版本一步一步用上来的，研究了半天发现不了原因，只有退回v5.0.0.1，于是就正常了！总之来说就是新版本不能用，但退回老版本就正常，特此报告一下，请完善一下，谢谢

**Comment by HMBSbige** [comment]
你这等于没说啊，要么发日志，系统版本等

都不知道什么问题，我怎么解决

**Comment by HMBSbige** [comment]
https://github.com/HMBSbige/ShadowsocksR-Windows/issues/55#issuecomment-526803917

**Comment by HMBSbige** [comment]
https://github.com/HMBSbige/ShadowsocksR-Windows/issues/55#issuecomment-526806095

**Comment by haley924** [comment]
> 你这等于没说啊，要么发日志，系统版本等
> 
> 都不知道什么问题，我怎么解决

对不起，我是菜鸟，请原谅，我是WIN10系统，48和netcore都是相同的问题。日志是SSR选项中的显示日志吗？是全部复制下来给你看，还是复制到记事本上给你看，我对这方面是菜鸟，不要介意，嘿嘿，但还是想说你辛苦了

**Comment by HMBSbige** [comment]
win10的什么版本

显示日志直接发截图，贴代码都行

**Comment by haley924** [comment]
> win10的什么版本
> 
> 显示日志直接发截图，贴代码都行
> 
> 我重新打包了，你重新下再试试

win10 64位 1903版本 ,现在这个日志是用的是刚下的ShadowsocksR-netcore-win64
[2019-08-31 23:19:44] ShadowsocksR started on port 1080
[2019-08-31 23:19:54] [Info] Connect api.github.com:443 via server host:8388
[2019-08-31 23:19:54] [Info] DNS query api.github.com answer 13.250.168.23
[2019-08-31 23:19:54] [Info] DNS nolock query api.github.com answer 13.250.168.23
[2019-08-31 23:19:54] [Info] DNS query server host failed.
[2019-08-31 23:19:54] [Info] Connect 13.250.168.23:443 via server host:8388
[2019-08-31 23:19:54] [Info] DNS query server host failed.
[2019-08-31 23:19:54] [Info] Connect 13.250.168.23:443 via server host:8388
[2019-08-31 23:19:54] [Info] DNS query server host failed.
[2019-08-31 23:19:54] [Info] Disconnect 13.250.168.23:443
[2019-08-31 23:19:54] [Error] System.Net.WebException: An error occurred while sending the request. The response ended prematurely.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
[2019-08-31 23:20:09] 
============================
none  NoneEncryptor
aes-128-cbc  StreamOpenSSLEncryptor
aes-192-cbc  StreamOpenSSLEncryptor
aes-256-cbc  StreamOpenSSLEncryptor
aes-128-ctr  StreamOpenSSLEncryptor
aes-192-ctr  StreamOpenSSLEncryptor
aes-256-ctr  StreamOpenSSLEncryptor
aes-128-cfb  StreamOpenSSLEncryptor
aes-192-cfb  StreamOpenSSLEncryptor
aes-256-cfb  StreamOpenSSLEncryptor
aes-128-cfb8  StreamOpenSSLEncryptor
aes-192-cfb8  StreamOpenSSLEncryptor
aes-256-cfb8  StreamOpenSSLEncryptor
aes-128-cfb1  StreamOpenSSLEncryptor
aes-192-cfb1  StreamOpenSSLEncryptor
aes-256-cfb1  StreamOpenSSLEncryptor
camellia-128-cfb  StreamOpenSSLEncryptor
camellia-192-cfb  StreamOpenSSLEncryptor
camellia-256-cfb  StreamOpenSSLEncryptor
bf-cfb  StreamOpenSSLEncryptor
cast5-cfb  StreamOpenSSLEncryptor
idea-cfb  StreamOpenSSLEncryptor
rc2-cfb  StreamOpenSSLEncryptor
rc4  StreamOpenSSLEncryptor
rc4-md5  StreamOpenSSLEncryptor
rc4-md5-6  StreamOpenSSLEncryptor
seed-cfb  StreamOpenSSLEncryptor
salsa20  StreamSodiumEncryptor
chacha20  StreamSodiumEncryptor
xsalsa20  StreamSodiumEncryptor
xchacha20  StreamSodiumEncryptor
chacha20-ietf  StreamSodiumEncryptor
============================

[2019-08-31 23:20:16] [Info] Connect raw.githubusercontent.com:443 via server host:8388
[2019-08-31 23:20:16] [Info] DNS query raw.githubusercontent.com answer 151.101.228.133
[2019-08-31 23:20:16] [Info] DNS nolock query raw.githubusercontent.com answer 151.101.228.133
[2019-08-31 23:20:16] [Info] DNS query server host failed.
[2019-08-31 23:20:17] [Info] Connect 151.101.228.133:443 via server host:8388
[2019-08-31 23:20:17] [Info] DNS query server host failed.
[2019-08-31 23:20:17] [Info] Connect 151.101.228.133:443 via server host:8388
[2019-08-31 23:20:17] [Info] DNS query server host failed.
[2019-08-31 23:20:17] [Info] Disconnect 151.101.228.133:443
[2019-08-31 23:20:17] [Error] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.
 ---> System.Net.WebException: An error occurred while sending the request. The response ended prematurely.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at System.Net.DownloadStringCompletedEventArgs.get_Result()
   at Shadowsocks.Controller.ChnDomainsAndIPUpdater.HttpDownloadSSCNIPTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-08-31 23:20:32] ShadowsocksR started on port 1080
[2019-08-31 23:20:40] [Info] Connect rss-node.com:443 via server host:8388
[2019-08-31 23:20:40] [Info] DNS query rss-node.com answer 104.26.6.174
[2019-08-31 23:20:40] [Info] DNS nolock query rss-node.com answer 104.26.6.174
[2019-08-31 23:20:40] [Info] DNS query server host failed.
[2019-08-31 23:20:41] [Info] Connect 104.26.6.174:443 via server host:8388
[2019-08-31 23:20:41] [Info] DNS query server host failed.
[2019-08-31 23:20:41] [Info] Connect 104.26.6.174:443 via server host:8388
[2019-08-31 23:20:41] [Info] DNS query server host failed.
[2019-08-31 23:20:41] [Info] Disconnect 104.26.6.174:443
[2019-08-31 23:20:52] ShadowsocksR started on port 1080
[2019-08-31 23:20:52] ShadowsocksR started on port 1080
[2019-08-31 23:20:53] ShadowsocksR started on port 1080
[2019-08-31 23:20:59] [Info] Connect raw.githubusercontent.com:443 via server host:8388
[2019-08-31 23:20:59] [Info] DNS nolock query raw.githubusercontent.com answer 151.101.228.133
[2019-08-31 23:20:59] [Info] DNS query server host failed.
[2019-08-31 23:20:59] [Info] Connect 151.101.228.133:443 via server host:8388
[2019-08-31 23:20:59] [Info] DNS query server host failed.
[2019-08-31 23:20:59] [Info] Connect 151.101.228.133:443 via server host:8388
[2019-08-31 23:20:59] [Info] DNS query server host failed.
[2019-08-31 23:20:59] [Info] Disconnect 151.101.228.133:443
[2019-08-31 23:20:59] [Error] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.
 ---> System.Net.WebException: An error occurred while sending the request. The response ended prematurely.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at System.Net.DownloadStringCompletedEventArgs.get_Result()
   at Shadowsocks.Controller.ChnDomainsAndIPUpdater.HttpDownloadSSCNIPTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-08-31 23:21:34] ShadowsocksR started on port 1080
[2019-08-31 23:21:47] config.checkSwitchAutoCloseAll:False
[2019-08-31 23:21:48] ShadowsocksR started on port 1080
[2019-08-31 23:22:01] ShadowsocksR started on port 1080
[2019-08-31 23:22:15] [Info] Connect raw.githubusercontent.com:443 via video52.cdn.globalnetworktraffic.com:1099
[2019-08-31 23:22:15] [Info] DNS nolock query raw.githubusercontent.com answer 151.101.228.133
[2019-08-31 23:22:15] [Info] DNS query video52.cdn.globalnetworktraffic.com answer 60.246.173.103
[2019-08-31 23:22:16] [Info] Connect ftp.apnic.net:443 via video52.cdn.globalnetworktraffic.com:1099
[2019-08-31 23:22:16] [Info] DNS query ftp.apnic.net answer 202.12.29.205
[2019-08-31 23:22:16] [Info] DNS nolock query ftp.apnic.net answer 202.12.29.205
[2019-08-31 23:22:16] [Info] Disconnect 151.101.228.133:443
[2019-08-31 23:22:24] [Info] Connect raw.githubusercontent.com:443 via video52.cdn.globalnetworktraffic.com:1099
[2019-08-31 23:22:24] [Info] DNS nolock query raw.githubusercontent.com answer 151.101.228.133
[2019-08-31 23:22:24] [Info] Disconnect 202.12.29.205:443
[2019-08-31 23:22:25] [Info] Disconnect 151.101.228.133:443
[2019-08-31 23:22:26] [Info] Detected: PAC file 'pac.txt' was created.
[2019-08-31 23:22:26] [Info] Detected: PAC file 'pac.txt' was changed.
[2019-08-31 23:23:07] ShadowsocksR started on port 1080
[2019-08-31 23:24:49] ShadowsocksR started on port 1080
[2019-08-31 23:24:58] config.checkSwitchAutoCloseAll:False
[2019-08-31 23:24:58] ShadowsocksR started on port 1080
[2019-08-31 23:26:42] ShadowsocksR started on port 1080
[2019-08-31 23:28:19] ShadowsocksR started on port 1080
[2019-08-31 23:28:25] ShadowsocksR started on port 1080

**Comment by HMBSbige** [comment]
`[2019-08-31 23:20:59] [Info] Connect 151.101.228.133:443 via server host:8388`

你都没选服务器啊...

**Comment by haley924** [comment]
q 

> `[2019-08-31 23:20:59] [Info] Connect 151.101.228.133:443 via server host:8388`
> 
> 你都没选服务器啊...
> 
> 设置服务器和选服务器这种基本操作都不会？

我选了服务器，然后打开网页，一直读取地址中。。。最后变成
![ScreenShot_20190831232745](https://user-images.githubusercontent.com/35114399/64066128-db45b100-cc48-11e9-8ddb-0df3a45295fc.png)
![ScreenShot_20190831232802](https://user-images.githubusercontent.com/35114399/64066129-db45b100-cc48-11e9-86ea-6d7f83cc4c9e.png)

**Comment by haley924** [comment]
比如说我选了某深港服务器，打开网页就这样，进不去。。如果是老版本，随便选个节点就可以进去

**Comment by HMBSbige** [comment]
日志只能看出你用的是默认服务器

**Comment by haley924** [comment]
2019-08-31 23:28:25] ShadowsocksR started on port 1080
[2019-08-31 23:42:02] config.checkSwitchAutoCloseAll:False
[2019-08-31 23:42:02] ShadowsocksR started on port 1080

**Comment by haley924** [comment]
算了，我还是用V5.0.0.1老版本吧，在V5.0以前全部都能用，费心了，感谢

**Comment by HMBSbige** [comment]
我觉得你的问题太小白了，直接新版本覆盖就行了，你这很可能的就没导入设置

**Comment by haley924** [comment]
> 我觉得你的问题太小白了，直接新版本覆盖就行了，你这很可能的就没导入设置

尝试过，用新版本导入老版本，还是一样的。。退回老版本就好了

**Comment by haley924** [comment]
比如我现在直接删掉TEMP文件夹，然后复盖老版的EXE文件，就又好了，无语中，哈哈

**Comment by HMBSbige** [comment]
日志就只看到你选的是默认服务器

更新直接替换exe就行了

以后这种小白问题问你的机场去
